version: "3"
services:
  decent-slack-receiver:
    image: "decentstudio/decent-slack-receiver"
    depends_on:
      - rabbitmq
    env_file:
      - .env
    ports:
      - "8080:80"
  decent-news-distributor:
    image: "decentstudio/decent-news-distributor"
    depends_on:
      - rabbitmq
    env_file:
      - .env
    ports:
      - "8081:80"
  rabbitmq:
    image: "rabbitmq:management-alpine"
    ports:
      - "15672:15672"
