version: "3"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672
  couchdb:
    image: klaemo/couchdb
    ports:
      - 5984:5984
  redis:
    image: redis:alpine
